version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - $HOST:$PORT:5432
    environment:
      POSTGRES_USER: $USER
      POSTGRES_PASSWORD: $PASS
      POSTGRES_DB: $DB
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
